const API_RESPONSE = {
  REQUEST_SUCCESSFUL: "request successful",
  INVALID_REQUEST: "invalid request",
  FORBIDDEN: "forbidden",
  LOGIN_SUCCESSFUL: "login successful",
  LOGOUT_SUCCESSFUL: "logout successful",
  CREATED: "created",
  UPDATED: "updated",
  NOT_FOUND: "not found",
  UNAUTHORIZED: "unauthorized",
  EXCEPTION_OCCURRED: "exception occurred",
  USER_CREATED: "user created",
  USER_UPDATED: "user updated",
  USER_DELETED: "user deleted",
  USER_NOT_FOUND: "user not found",
  FAILED_TO_CREATE_USER: "failed to create user",
  FAILED_TO_DELETE_USER: "failed to delete user",
  FAILED_TO_REGISTER_USER: "failed to register user",
  FAILED_TO_LOGIN_USER: "failed to login user",
  FAILED_TO_UPDATE_USER: "failed to update user",
  FAILED_TO_READ_USER: "failed to read user",
  FAILED_TO_GET_REQUESTS: "failed to get requests",
  FAILED_TO_GET_FEED: "failed to get feed",
  PASSWORD_UPDATED_SUCCESSFULLY: "password updated successfully",
  FAILED_TO_UPDATE_PASSWORD: "failed to update password",
  INVALID_CREDENTIALS: "invalid credentials",
};

export default API_RESPONSE;
